# Generated by Django 3.2.11 on 2022-01-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('foto', models.CharField(blank=True, max_length=100, null=True)),
                ('classe', models.CharField(max_length=100)),
            ],
        ),
    ]
